### ISSUE TITLE
"Improving the UX is the developers job" talk does not belong to 2018 schedule

### ISSUE THREAD

**Issue by simonihmig** [emberfest/emberfest.github.io#129]
This talk is listed on the 2018 schedule: https://emberfest.eu/schedule/#jakub-niechcial, but was from 2017.

**Comment by marcoow** [comment]
@wadie: can you have a look?

**Comment by wadie** [comment]
True, that's an older talk and I've removed it now.

Thanks for the report @simonihmig 👍
