### ISSUE TITLE
Responsive issue on website

### ISSUE THREAD

**Issue by romgere** [emberfest/emberfest.github.io#131]
Hi, here is the problem :

![image](https://user-images.githubusercontent.com/13900970/45207645-c8dca580-b288-11e8-88a1-75ff090ce508.png)

I'am not able to reproduce in desktop browser.

I wonder if it's not a chrome bug  anymore (when renderinf the svg).

**Comment by marcoow** [comment]
@wadie: can you have a look?

**Comment by wadie** [comment]
I'm not able to reproduce the issue using Firefox or Chrome, on the desktop as well as mobile.
![screenshot](https://user-images.githubusercontent.com/1206307/45213067-d0a34680-b296-11e8-89e4-1a88073e0aa8.jpg)

Which version of Google Chrome and Android are you using ?

**Comment by romgere** [comment]
Chrome : 68
Android : 7.1.2

I really think it's a random rendering bug with chrome. 

I take a record with remote debug in chrome dev tools :

![peek 07-09-2018 14-30](https://user-images.githubusercontent.com/13900970/45219390-08b48480-b2ab-11e8-8e10-350de2cb19be.gif)

After some refresh, the image is correctly render (or not, it's very random behavior)
