### ISSUE TITLE
Update Website for 2019 Conference

### ISSUE THREAD

**Issue by ghislaineguerin** [emberfest/emberfest.github.io#142]
The Emberfest page must be updated to promote the upcoming October 2019 conference.
I have attached the files needed for the header update and will upload the footer mascot as well.

SVG for the header:
https://drive.google.com/open?id=1FgwfGga56slCQiv5uJdnUtDGFxzoeZ1F
PNG:
https://drive.google.com/open?id=1C7pOgutP_X6Nd3NSUwJrmHQceCbh2ShJ
MASCOT:
https://drive.google.com/open?id=1J9vekIEDo-V-R32JjP-cW3P6F6epuNHq

**Comment by ghislaineguerin** [comment]
@wadie Can you take this issue? I cannot assign it to you for some reason.

**Comment by marcoow** [comment]
@ghislaineguerin I think we should make the mascot smaller - we'll be using it in the footer of the website and for the Twitter profile pic for example so I think we'll want something that is only the had probably. Also I think the sunglasses should remain orange - that's sort of a trademark EmberFest think I guess…
