### ISSUE TITLE
Publish Sponsor Prospectus

### ISSUE THREAD

**Issue by ghislaineguerin** [emberfest/emberfest.github.io#147]
Please add the following file to replace the pdf at https://emberfest.eu/sponsorship.pdf
[prospectus.pdf](https://github.com/emberfest/emberfest.github.io/files/3078164/prospectus.pdf)

**Comment by wadie** [comment]
I believe some changes are required to that pdf as was discussed on basecamp.

**Comment by wadie** [comment]
Closed by PR#149
