### ISSUE TITLE
Add pay-by-invoice note

### ISSUE THREAD

**Issue by marcoow** [emberfest/emberfest.github.io#15]
Companies will want to pay by invoice which should be no problem for us. ti.to doesn't seem to support that but we can simply add a note saying something like "please contact us if you'd like to pay by invoice".

**Comment by jkintscher** [comment]
I have added the note to the bottom of the ticket page:

![](https://monosnap.com/file/ef8WK74SfIFQZVVjnaSMaZEzb4kkoU.png)

We just need to update the email with a general @emberfest.eu one. Will get that from Joachim tomorrow to set it as the main contact for Ti.to, but that’s a separate thing.
