### ISSUE TITLE
Make the possibility of sponsoring more salient

### ISSUE THREAD

**Issue by balinterdi** [emberfest/emberfest.github.io#153]
Currently we only have a small link in the footer. We should have a section relatively close to the top of the page.

**Comment by marcoow** [comment]
I guess we could have a link _"become a sponsor"_ at the bottom of the _"Sponsors"_ section?

**Comment by balinterdi** [comment]
Yeah, that could be the MVP, linking to the prospectus. Let's have a button below the last sponsor logo line.

Hmm, how about having at least a separate section with this blurb (taken from the prospectus):

> If you’re hiring or working with Ember.js in Europe, an EmberFest sponsorship is the best way to reach the continent’s most talented Ember.js developers. A limited number of sponsorship opportunities are available. 

And then the button I described.
