### ISSUE TITLE
Publish schedule

### ISSUE THREAD

**Issue by marcoow** [emberfest/emberfest.github.io#178]
…as we have decided on one and should let people know

**Comment by alexspeller** [comment]
**Sivakumar Kailasam**

![image](https://user-images.githubusercontent.com/1217/63649135-c2616b00-c731-11e9-9702-4494237577a9.png)

Siva is a member of the EmberJS Learning Team. He currently works at Smile.io building a rewards platform for online businesses. He is an avid contributor to open source, loves mentoring, really really enjoys coding & his matcha tea.

**Comment by marcoow** [comment]
done via #179
