### ISSUE TITLE
Newsletter subscription form doesn’t properly submit

### ISSUE THREAD

**Issue by jkintscher** [emberfest/emberfest.github.io#224]
Instead of subscribing to the mailing list directly from our website, the form currently just opens https://emberfest.us16.list-manage.com/subscribe/post?u=214d2441f851e9fa9c9dfc96d&id=fe26330e01, and only recognizes the email address entered, the other fields remain empty. There, you have to fill in everything again and submit it.

Not sure why it broke, though, as it doesn’t seem like the code has changes since last year:
https://github.com/emberfest/emberfest.github.io/blame/master/index.html#L230

So maybe it’s a configuration thing on Mailchimp’s site?

**Comment by marcoow** [comment]
submitting to a page on mailchimp's side is how this is supposed to work I think but of course all fields should be recognized
