### ISSUE TITLE
Add content

### ISSUE THREAD

**Issue by marcoow** [emberfest/emberfest.github.io#3]
We'll need to add some more text etc. Maybe we can port some of the old content over? I think having only one page is fine though - don't think we need to artificially bloat the page.

**Comment by alexspeller** [comment]
Yes, keeping it simple for now and only having one page makes sense I think

**Comment by marcoow** [comment]
I think the content is at a state where it's sufficient for publishing. We can always improve it later on of course.

**Comment by marcoow** [comment]
done
