### ISSUE TITLE
Announce Phorest as a partner sponsor

### ISSUE THREAD

**Issue by marcoow** [emberfest/emberfest.github.io#303]
This is the logo:

![phorest-logo](https://user-images.githubusercontent.com/1510/185340793-58a7b5b5-c280-4a7f-a435-8117f005a006.svg)

**Comment by inesilva** [comment]
Checking abstract I see that all logos are in black:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/15367376/185634868-0035e58e-9f5c-4bc0-9e10-90e76ef372d7.png">
