### ISSUE TITLE
Write blog post about EmberFest'16 (Budapest)

### ISSUE THREAD

**Issue by balinterdi** [emberfest/emberfest.github.io#31]
A write-up about last year's EmberFest would be great and might drive a few sales. I volunteered to write the blog post and will ask @alexspeller to pass me some majestic photos.

**Comment by alexspeller** [comment]
![2016-10-28 19 54 33](https://user-images.githubusercontent.com/1217/28999577-286c70a6-7a4b-11e7-9222-96c4e870cf20.jpg)
![2016-10-28 19 53 35](https://user-images.githubusercontent.com/1217/28999578-288c0f42-7a4b-11e7-86ac-59038383383e.jpg)
![2016-10-28 19 51 37](https://user-images.githubusercontent.com/1217/28999579-288fcd6c-7a4b-11e7-8e61-ff92dba442ea.jpg)
![Uploading 2016-10-28 18.57.27.jpg…]()
![2016-10-28 18 55 37](https://user-images.githubusercontent.com/1217/28999581-28a655c8-7a4b-11e7-8f0d-3ed4a82a3721.jpg)
![2016-10-26 10 29 58](https://user-images.githubusercontent.com/1217/28999582-28a7add8-7a4b-11e7-8433-396155b5d0ed.jpg)



I thought I had more but these are the ones I have from last year

**Comment by balinterdi** [comment]
PR is at https://github.com/emberfest/emberfest.github.io/pull/46

**Comment by marcoow** [comment]
closed via #46
