### ISSUE TITLE
Announce simplabs as diner sponsor

### ISSUE THREAD

**Issue by marcoow** [emberfest/emberfest.github.io#313]
We'll be sponsoring the closing diner. That's a new sponsorship tier that's not in the prospectus. It should get it's own section and have the same size as premier partner sponsor logos.

**Comment by inesilva** [comment]
> It should get it's own section and have the same size as premier partner sponsor logos.
Does this mean we want to have it in a different section inside sponsors, or in a section next to the dinner?

Examples of what I mean:
![image](https://user-images.githubusercontent.com/15367376/186380224-4de69e9f-2e18-4949-af9f-ae5aaacccd8a.png)

or:
![image](https://user-images.githubusercontent.com/15367376/186380375-7d2674ef-4db8-48b6-b61c-245725a08c4b.png)

**Comment by jkintscher** [comment]
I think you can even just make it “Dinner Sponsor”, we’ll only ever have one 😊  Same will be the case with the (hopefully soon) upcoming ”Livestream Sponsor” section.
