### ISSUE TITLE
Add "presented by" section

### ISSUE THREAD

**Issue by marcoow** [emberfest/emberfest.github.io#314]
We want to add a section to the website that lists the presenters of the event. That's simplabs, Joschka Kintscher, and Balint Erdi.

We should add that section below the sponsors section with

* title: "Presenters"
* content: text "EmberFest is presented by", images of the 3 presenters (our logo, photos for Joschka and Balint), each one with a web link and Twitter profile link

Overall, that section can be visually the same as the "Speakers" section.

**Comment by marcoow** [comment]
@joachimhs @balinterdi can you provide photos to put on the site as well as links?

**Comment by inesilva** [comment]
@balinterdi @joachimhs I added your GitHub photos and your links from there as well, I placed you as reviewers of the PR so if there is something you want to change let me know :)

**Comment by jkintscher** [comment]
@inesilva @marcoow  Joachim hasn’t been involved in EmberFest since 2015. I presume you meant me 😉  My handle (everwhere) is @jkintscher 😜

**Comment by marcoow** [comment]
yes I meant @jkintscher of course :)
