### ISSUE TITLE
Add missing information for `Panel Day 2`: The Future of Ember

### ISSUE THREAD

**Issue by oscard0m** [emberfest/emberfest.github.io#338]
https://deploy-preview-326--silly-leavitt-2e0668.netlify.app/schedule/#panel-future-of-ember

@balinterdi can you validate the panellists and description are already correct?

![image](https://user-images.githubusercontent.com/2574275/188406703-c4b0af7b-7889-4112-951c-9be6dfaf462e.png)

Don't include Aaron Chambers

**Comment by balinterdi** [comment]
It's not there yet (that's okay, because @marcoow will prove the panelists later), is it?

<img width="738" alt="Screenshot 2022-09-02 at 19 02 00" src="https://user-images.githubusercontent.com/5022/188203177-0daa6ce5-38cf-4d9d-b4a5-2fadf15cccce.png">

**Comment by marcoow** [comment]
@balinterdi see panel details here: https://3.basecamp.com/4551353/buckets/26511198/todos/5148323139

**Comment by oscard0m** [comment]
I don't have access to that link so I will need you to share the details on this issue.
@balinterdi
