### ISSUE TITLE
Add info on when doors open to schedule

### ISSUE THREAD

**Issue by marcoow** [emberfest/emberfest.github.io#371]
Add an entry to the schedule for both days:

9:00 - 10:00 – Doors open & Breakfast

**Comment by oscard0m** [comment]
@inesilva can you take this one? I think we can use the same approach we use for Lunch and Dinner with the [`isBreakTime`](https://github.com/emberfest/emberfest.github.io/blob/59bed136deed67de5afe4f8ec86ca75a423dfe2e/_data/schedule/day1.yml#L54)
