### ISSUE TITLE
Release conference diner information

### ISSUE THREAD

**Issue by marcoow** [emberfest/emberfest.github.io#377]
We need to put the section with the conference closing diner information on the landing page – have forgotten so far so needs to happen ASAP (= monday) now…

**Comment by marcoow** [comment]
@jkintscher can you comment the relevant info here?

**Comment by jkintscher** [comment]
It’s going to be at http://www.lesjardinsdupontneuf.com/galerie.html

Starting time is 8pm, until midnight. Food is served until 10pm. Drinks all night.
