### ISSUE TITLE
Make this look better

### ISSUE THREAD

**Issue by marcoow** [emberfest/emberfest.github.io#4]
I'm obviously no styling guru…

**Comment by alexspeller** [comment]
Who is the best to look at this? I'm not awesome at design either

**Comment by marcoow** [comment]
We might be able to put resources on this - not before end of next week though.

**Comment by marcoow** [comment]
I think the look of the page is at a state where it's sufficient for publishing. We can always improve it later on of course.

**Comment by marcoow** [comment]
done
