### ISSUE TITLE
Update portraits

### ISSUE THREAD

**Issue by davidhajba** [emberfest/emberfest.github.io#411]
Please update the portraits (new ones in assets)

assets are [HERE](https://shared-assets.adobe.com/link/1a48c974-c6cc-4c69-5572-4f68c4ea2aaa)

**Comment by oscard0m** [comment]
By portraits you mean the profile pictures of organizers and past speakers? @davidhajba

**Comment by davidhajba** [comment]
@oscard0m - yes.
I updated the colors.

**Comment by oscard0m** [comment]
@davidhajba, The profile pictures of Baling and Joschka have been exported with a surrounding transparent background. Can you fix that?

![image](https://github.com/emberfest/emberfest.github.io/assets/2574275/eb6f8d3c-6493-49f4-9f05-9a70a2377569)

**Comment by davidhajba** [comment]
Updated - thanks for highlighting it @oscard0m 
It was a tricky one :)
