### ISSUE TITLE
Update video thumbnail 

### ISSUE THREAD

**Issue by davidhajba** [emberfest/emberfest.github.io#412]
Please update the 'Ember {{fest}} 2022' video thumbnail (see in Sketch)

[HERE](https://www.sketch.com/s/150ed20a-d7c3-46a1-8151-89fba683acae/a/27e9GRy) is the Sketch version

**Comment by oscard0m** [comment]
Right now, we are using YouTube embedded and it's youtube the one suggesting a thumbnail. My first question is: **Do we explicitly want to use YouTube embedded video?** (maybe we want to track some views, clicks, comments, etc...)

- If the answer is **Yes**, we would need to customize the thumbnail in YouTube's Settings: https://support.google.com/youtube/answer/72431?hl=en&co=GENIE.Platform%3DAndroid#zippy=%2Cthumbnail-policies%2Ccustom-thumbnail-limits
- If the answer is **No**, I suggest uploading the video and using a native player where we can specify the poster we want:

```html
<video width="320" height="240" controls poster="YourImageURL">
    <source src="YourVideoURL" type="video/mp4">
</video>
```

For this step, I would need the video file.

Can you discover this for me @davidhajba?

**Comment by davidhajba** [comment]
hey @oscard0m 
I cannot answer your question, it's not my decision.

To keep it simple, as it is youtube now, imo maybe we can keep it like this and update the thumbnail.
Shall I ask Emma? Or what do you think?

**Comment by oscard0m** [comment]
> hey @oscard0m I cannot answer your question, it's not my decision.
> 
> To keep it simple, as it is youtube now, imo maybe we can keep it like this and update the thumbnail. Shall I ask Emma? Or what do you think?

I'm asking in #emeberfest Slack channel.

**Comment by davidhajba** [comment]
hey @oscard0m 

as we cannot change the video thumbnail as we don't have access to the youtube account, 
could we please use the other option, and using a native player as we do with EuroRust as well ?

It would be important to use a consistent design and currently the video really thumbnail stands out.
Especially because we need stronger connection with the social media templates - see [HERE](https://www.sketch.com/s/150ed20a-d7c3-46a1-8151-89fba683acae/v/mdywD8/p/963260F2-3AD2-4430-B4E9-649A0D087CC6/canvas?posX=-3481.9764879220884&posY=-11382.838103797445&zoom=0.2087448537349701)

**Comment by oscard0m** [comment]
> **Do we explicitly want to use YouTube embedded video?** (maybe we want to track some views, clicks, comments, etc...)

Can we validate not to use YouTube in the Slack thread we already have open? It's unclear to me if there is any need to use YouTube (maybe we want to track some views, clicks, comments, etc...).

**Comment by marcoow** [comment]
we're leaving this as is – not worth spending more time on this
