### ISSUE TITLE
Add sponsors

### ISSUE THREAD

**Issue by marcoow** [emberfest/emberfest.github.io#420]
We're signing up the first sponsors that need to be added to the website. We'll need one pull request each for:

* redpencil at partner level – can reuse image and URL from previous years
* Qonto at partner level – can reuse image and URL from previous years
* Mainmatter as dinner sponsor – can reuse image and URL from previous years

### Resources

* Designs: https://www.sketch.com/s/150ed20a-d7c3-46a1-8151-89fba683acae/a/MmlKpPl

**Comment by marcoow** [comment]
@oscard0m will you be able to do this next week, assuming design is ready monday?

**Comment by oscard0m** [comment]
> @oscard0m will you be able to do this next week, assuming design is ready monday?

Yes
